### ISSUE TITLE
Jellyfin 10.7, Auto Organize 9.0 : Uncaught ReferenceError: define is not defined  at configurationpage?name=AutoOrganizeLogJs:1

### ISSUE THREAD

**Issue by Sabotageur** [jellyfin/jellyfin-plugin-autoorganize#58]
Since updating to Jellyfin 10.7 on Raspbian, when accessing the Auto Organize UI, only few elements load :
![AutoOrganize](https://user-images.githubusercontent.com/35267267/111026787-94fc1100-83ec-11eb-97a6-f7e3f15af1ba.JPG)

In the Web console, it appears that requireJS is missing, as the line 

    define(['globalize', 'serverNotifications', 'events', 'scripts/taskbutton', 'datetime', 'loading', 'libraryMenu', 'paper-icon-button-light', 'emby-button', 'detailtablecss'], function (globalize, serverNotifications, events, taskButton, datetime, loading, libraryMenu) {

triggers the error 

    Uncaught ReferenceError: define is not defined
    at configurationpage?name=AutoOrganizeLogJs:1

How can I add requireJS to my jellyfin server ? I'm not using docker but I installed jellyfin a while ago following these instructions : 
https://jellyfin.org/docs/general/administration/installing.html#debian

**Comment by crobibero** [comment]
You cant add requireJS to the server, the plugin needs to be updated.

**Comment by Sabotageur** [comment]
Thank you for your reply, but to be sure, does that mean that the plugin itself needs a v10 to work here, or that I need to do something on my end ?

**Comment by crobibero** [comment]
The plugin needs a v10. If you know JS and have time feel free to make a PR fixing it :)
Otherwise one of us will get to it eventually

**Comment by wlademirgomes** [comment]
Any predictions for version 10 or alternative?

**Comment by gopaljigaur** [comment]
@crobibero Are there any instructions on changing a plugin to a newer version? What exactly needs to be done to update it to v10?

**Comment by sabeechen** [comment]
I would like to help fix this, as I really like this plugin, but I am not familiar with Jellyfin's internal architecture or processes and could use some pointers for where to dig in.  What I *think* I've determined from poking around a bit is:

- The problem is purely in the javascript for the web front-end, not any of the c# code.
- The plugin currently uses RequireJS to load all of its dependencies.
- The [Jellyfin Frontend](https://github.com/jellyfin/jellyfin-web) previously used RequireJS, but at some point [moved away](https://github.com/jellyfin/jellyfin-web/issues/1143).  Its not clear to me from that discussion if an API that this plugin can use is still available.
- This plugin wasn't considered when the frontend moved away from RequireJS.

I tried looking around at the source code for a bunch of the other [official plugins](https://jellyfin.org/docs/general/server/plugins/index.html), but I couldn't find any that indicate how a plugin interacts with many of the frontend dependencies that AutoOrganize uses, such as [serverNotifications](https://github.com/jellyfin/jellyfin-web/blob/5c09077a2f12ae44e7b7d356ea8d9f35862b0b60/src/scripts/serverNotifications.js) or [datetime](https://github.com/jellyfin/jellyfin-web/blob/5c09077a2f12ae44e7b7d356ea8d9f35862b0b60/src/scripts/datetime.js).  Is it still possible to use these objects in a plugin, or does  AutoOrganize need a more significant rewrite to work properly?  I tried rewriting some small parts of the AutoOrganize plugin as a module with ```import datetime from /scripts/datetime```, etc but it doesn't seem to do the trick.

**Comment by gopaljigaur** [comment]
I would also like to have this plugin, and I also tried following some instructions for contributing to the project but failed to make it work. Devs, can you please give an estimate of when this would be fixed?

**Comment by mark-monteiro** [comment]
@gopaljigaur Looks like @grafixeyehero is working on this in https://github.com/jellyfin/jellyfin-plugin-autoorganize/pull/67

**Comment by gopaljigaur** [comment]
@mark-monteiro Thanks for letting me know. Hopefully, the updated version gets released soon.

**Comment by straszydto** [comment]
Any idea if this has been fixed yet?
